config/routes.rb
Rails.application.routes.draw do
  resources :static_pages
  get "/", to:'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: %i[ show edit update destroy ]

  # GET /static_pages or /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1 or /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages or /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: "Static page was successfully created." }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1 or /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: "Static page was successfully updated." }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1 or /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: "Static page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def static_page_params
      params.fetch(:static_page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicboxxx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/_form.html.erb
<%= form_with(model: static_page, local: true) do |form| %>
  <% if static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form', static_page: @static_page %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>The Incredible Music Box</h1>

<div>
  <div class="key" id="k81">
    <kbd>q</kbd>
    <span>boom</span>
  </div>
  <div class="key" id="k83">
    <kbd>s</kbd>
      <span>clap</span>
  </div>
  <div class="key" id="k68">
    <kbd>d</kbd>
        <span>hihat</span>
  </div>
  <div class="key" id="k70">
    <kbd>f</kbd>
          <span>kick</span>
  </div>
  <div class="key" id="k71">
    <kbd>g</kbd>
    <span>openhat</span>
  </div>
</div>

<%= audio_tag "boom.wav", id:"audio81" %>
<%= audio_tag "clap.wav", id:"audio83" %>
<%= audio_tag "hihat.wav", id:"audio68" %>
<%= audio_tag "kick.wav", id:"audio70" %>
<%= audio_tag "openhat.wav", id:"audio71" %>

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form', static_page: @static_page %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>